### PR TITLE
Fixed issue for installing Enclave on Amazon Linux

### PR DESCRIPTION
**Pull request by ghost**
Related to #22 

Instead of doing a lot of else ifs i've instead switched to using `return` this will allow us to return when we've found a distro but continue the checks in the situation of `RHEL` based distros where they can match multiple IF statements for example 

```conf
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_lin
```

This would trigger 2 of our ifs so let's let it check both and see which it matches rather than only let it select the first it comes across.

### CODE REVIEW

**Comment by enclave-marc-barry** [comment]
Nice Tom, how does this look on at AWS Linux 2 host now?

**Comment by ghost** [comment]
It will still do a manual install but should no longer provide the Error (that error was partially because i wasn't correctly escaping a string that could result from a missing macro from the RPM command)

**Comment by enclave-marc-barry** [comment]
Good fix! Will leave it to Charlie or Alistair to review the code changes

**Review by enclave-alistair — APPROVED** [review]
LGTM

**Pull request merged**
